name: social_alert_app
description: Show your world as it is.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  form_field_validator:
  flutter_secure_storage:
  provider:
  http:
  image_picker:
  flutter_uploader:
  path:
  path_provider:
  geolocator: "< 6.0.0"
  timeago_flutter:
  google_maps_flutter:
  intl:
  exifdart:
  async:
  pull_to_refresh: "1.6.3" #wait for next flutter version
  flutter_typeahead:
  badges:
  fluster:
  device_info:
  photo_view:
  camera: "< 0.6.0"
  native_device_orientation:
  video_player:
  chewie:
  video_thumbnail:
  permission_handler:

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter:

  uses-material-design: true

  assets:
    - images/
    - images/flags/
